// Code generated by "goconfig -field Rename bool -option -output backup_config_generated.go"; DO NOT EDIT.

package backup

type ConfigItem[T any] struct {
	modified     bool
	value        T
	defaultValue T
}

func (s *ConfigItem[T]) Set(value T) {
	s.modified = true
	s.value = value
}
func (s *ConfigItem[T]) Get() T {
	if s.modified {
		return s.value
	}
	return s.defaultValue
}
func (s *ConfigItem[T]) Default() T {
	return s.defaultValue
}
func (s *ConfigItem[T]) IsModified() bool {
	return s.modified
}
func NewConfigItem[T any](defaultValue T) *ConfigItem[T] {
	return &ConfigItem[T]{
		defaultValue: defaultValue,
	}
}

type Config struct {
	Rename *ConfigItem[bool]
}
type ConfigBuilder struct {
	rename bool
}

func (s *ConfigBuilder) Rename(v bool) *ConfigBuilder {
	s.rename = v
	return s
}
func (s *ConfigBuilder) Build() *Config {
	return &Config{
		Rename: NewConfigItem(s.rename),
	}
}

func NewConfigBuilder() *ConfigBuilder { return &ConfigBuilder{} }
func (s *Config) Apply(opt ...ConfigOption) {
	for _, x := range opt {
		x(s)
	}
}

type ConfigOption func(*Config)

func WithRename(v bool) ConfigOption {
	return func(c *Config) {
		c.Rename.Set(v)
	}
}
