// Code generated by "stringer -type=LockExistence -output lockexistence_stringer_generated.go"; DO NOT EDIT.

package strategy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEnone-0]
	_ = x[LEexist-1]
}

const _LockExistence_name = "LEnoneLEexist"

var _LockExistence_index = [...]uint8{0, 6, 13}

func (i LockExistence) String() string {
	if i < 0 || i >= LockExistence(len(_LockExistence_index)-1) {
		return "LockExistence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LockExistence_name[_LockExistence_index[i]:_LockExistence_index[i+1]]
}
