// Code generated by "stringer -type=RepoExistence -output repoexistence_stringer_generated.go"; DO NOT EDIT.

package strategy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[REnone-0]
	_ = x[REexist-1]
}

const _RepoExistence_name = "REnoneREexist"

var _RepoExistence_index = [...]uint8{0, 6, 13}

func (i RepoExistence) String() string {
	if i < 0 || i >= RepoExistence(len(_RepoExistence_index)-1) {
		return "RepoExistence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RepoExistence_name[_RepoExistence_index[i]:_RepoExistence_index[i+1]]
}
