// Code generated by "dataclass -type RunnerConfig -field Repo string|Branch string|Pair *lock.Pair|Command git.Command -output run_dataclass_generated.go"; DO NOT EDIT.

package strategy

import (
	"berquerant/install-via-git-go/git"
	"berquerant/install-via-git-go/lock"
)

type RunnerConfig interface {
	Repo() string
	Branch() string
	Pair() *lock.Pair
	Command() git.Command
}
type runnerConfig struct {
	repo    string
	branch  string
	pair    *lock.Pair
	command git.Command
}

func (s *runnerConfig) Repo() string         { return s.repo }
func (s *runnerConfig) Branch() string       { return s.branch }
func (s *runnerConfig) Pair() *lock.Pair     { return s.pair }
func (s *runnerConfig) Command() git.Command { return s.command }
func NewRunnerConfig(
	repo string,
	branch string,
	pair *lock.Pair,
	command git.Command,
) RunnerConfig {
	return &runnerConfig{
		repo:    repo,
		branch:  branch,
		pair:    pair,
		command: command,
	}
}
