// Code generated by "stringer -type=UpdateSpec -output updatespec_stringer_generated.go"; DO NOT EDIT.

package strategy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[USunspec-0]
	_ = x[USforce-1]
	_ = x[USretry-2]
	_ = x[USnoupdate-3]
}

const _UpdateSpec_name = "USunspecUSforceUSretryUSnoupdate"

var _UpdateSpec_index = [...]uint8{0, 8, 15, 22, 32}

func (i UpdateSpec) String() string {
	if i < 0 || i >= UpdateSpec(len(_UpdateSpec_index)-1) {
		return "UpdateSpec(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateSpec_name[_UpdateSpec_index[i]:_UpdateSpec_index[i+1]]
}
